### PR TITLE
Switch packaging to Dist::Zilla

### PR DESCRIPTION
**Pull request by chrestomanci**
Add a dist.ini so that packaging and releases can be managed using Dist::Zilla.

Remove the now redundant Makefile.PL

NB: With this change, a copy of Module::Install will not be packaged into the
release tarball. Instead it is declared as a normal prequisite in Meta.yml.

### CODE REVIEW

**Comment by sartak** [comment]
Thanks @chrestomanci!

I don't think Module::Install is a dependency any more, could you remove it? The dzil config says to use MakeMaker, which fills the same role.

**Comment by chrestomanci** [comment]
OK @sartak.

I have updated the branch to remove Module::Install from dependencies.

**Comment by sartak** [comment]
Thanks very much!

**Comment by sartak** [comment]
Shipped 1.06 to CPAN. @chrestomanci++ :)

**Pull request merged**
